### ISSUE TITLE
Crash when taking photo

### ISSUE THREAD

**Issue by Zazo032** [Apparence-io/camera_awesome#118]
## Steps to reproduce

I can't always reproduce it, but it happens more frequently if you try to take a photo just after opening the camera (and already having a preview available)

## Logs

<details>

```
[ +945 ms] D/AndroidRuntime(18336): Shutting down VM
[        ] E/AndroidRuntime(18336): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(18336): Process: <elided>, PID: 18336
[        ] E/AndroidRuntime(18336): java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
[        ] E/AndroidRuntime(18336):     at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:738)
[        ] E/AndroidRuntime(18336):     at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1187)
[        ] E/AndroidRuntime(18336):     at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:1059)
[        ] E/AndroidRuntime(18336):     at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:188)
[        ] E/AndroidRuntime(18336):     at com.apparence.camerawesome.CameraPicture.captureStillPicture(CameraPicture.java:173)
[        ] E/AndroidRuntime(18336):     at com.apparence.camerawesome.CameraPicture.onStateChanged(CameraPicture.java:246)
[        ] E/AndroidRuntime(18336):     at com.apparence.camerawesome.CameraSession.setState(CameraSession.java:120)
[        ] E/AndroidRuntime(18336):     at com.apparence.camerawesome.CameraPreview.processCapture(CameraPreview.java:379)
[        ] E/AndroidRuntime(18336):     at com.apparence.camerawesome.CameraPreview.access$000(CameraPreview.java:45)
[        ] E/AndroidRuntime(18336):     at com.apparence.camerawesome.CameraPreview$1.onCaptureProgressed(CameraPreview.java:334)
[        ] E/AndroidRuntime(18336):     at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureProgressed$2$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:678)
[        ] E/AndroidRuntime(18336):     at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$7mSdNTTAoYA0D3ITDxzDJKGykz0.run(Unknown Source:8)
[        ] E/AndroidRuntime(18336):     at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/AndroidRuntime(18336):     at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/AndroidRuntime(18336):     at android.os.Looper.loop(Looper.java:246)
[        ] E/AndroidRuntime(18336):     at android.app.ActivityThread.main(ActivityThread.java:8512)
[        ] E/AndroidRuntime(18336):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(18336):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
[        ] E/AndroidRuntime(18336):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```
</details>

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A21s*  | *11*  |

**Comment by g-apparence** [comment]
As this seems coming more from device and camera2 I close this. 
Don't hesitate to open this again if 
- this bug still occurs
- you have more details to reproduce this.
