### ISSUE TITLE
Switching flash mode triggers an internal error

### ISSUE THREAD

**Issue by Zazo032** [Apparence-io/camera_awesome#171]
## Steps to Reproduce

Call `state.sensorConfig.switchCameraFlash`

## Expected results

`FlashMode` iterates to the next one

## Actual results

```
I/flutter (12799): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (12799): Bad state: Cannot add new events after calling close
I/flutter (12799): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
I/flutter (12799): #1      Subject._add (package:rxdart/src/subjects/subject.dart:151:17)
I/flutter (12799): #2      Subject.add (package:rxdart/src/subjects/subject.dart:141:5)
I/flutter (12799): #3      _StreamSinkWrapper.add (package:rxdart/src/subjects/subject.dart:215:13)
I/flutter (12799): #4      SensorConfig.setFlashMode (package:camerawesome/src/orchestrator/sensor_config.dart:76:31)
I/flutter (12799): <asynchronous suspension>
I/flutter (12799): ----------------------------------------------------
I/flutter (12799): Bad state: Cannot add new events after calling close
I/flutter (12799): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
I/flutter (12799): #1      Subject._add (package:rxdart/src/subjects/subject.dart:151:17)
I/flutter (12799): #2      Subject.add (package:rxdart/src/subjects/subject.dart:141:5)
I/flutter (12799): #3      _StreamSinkWrapper.add (package:rxdart/src/subjects/subject.dart:215:13)
I/flutter (12799): #4      SensorConfig.setFlashMode (package:camerawesome/src/orchestrator/sensor_config.dart:76:31)
I/flutter (12799): <asynchronous suspension>
```

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A21s*  | *12*  |

**Comment by Zazo032** [comment]
Using latest version of the repo:
```yaml
camerawesome:
    git:
      url: https://github.com/Apparence-io/camera_awesome.git
```
Using Flutter version `3.3.10`.

Using `CameraAwesomeBuilder.custom`:
```dart
CameraAwesomeBuilder.custom(
  enableAudio: false,
  saveConfig: SaveConfig.photo(
    pathBuilder: () => photoPath,
  ),
  builder: (CameraState state) {
    return IconButton(
      color: Colors.white,
      icon: Icon(_getFlashIcon(state.sensorConfig.flashMode)),
      key: const Key('flash_icon'),
      onPressed: state.sensorConfig.switchCameraFlash,
    );
  }
),
```

**Comment by apalala-dev** [comment]
This error appears because you are using an old sensorConfig which has been disposed internally.
You should use the stream version (sensorConfig$) as explained in #172.
However, I am not sure we should let things in this current state since they might not be easy to understand for newcomers.

I see two possible ways of dealing with this:
- Expose only streams and not getters since they might not be up-to-date
- Handle "disposed" cases and throw an error explaining what to do to not get this error
  - This would imply to add a check at every setter
  - Adding a check at each getter could also be useful since these getters might be out of date

What do you think @g-apparence ?
