### ISSUE TITLE
Orientation notifier being called after the activity is disposed

### ISSUE THREAD

**Issue by Max-Might** [Apparence-io/camera_awesome#32]
## Steps to Reproduce

My camera activity has an orientations notifier like from the example:
```dart
ValueNotifier<CameraOrientations> _orientationNotifier = ValueNotifier(CameraOrientations.PORTRAIT_UP);
```

In the `dispose()` method for the camera screen I dispose all notifiers like so:
```dart
  @override
  void dispose() {
    _iconsAnimationController.dispose();
    _orientationNotifier.dispose();
    _sensorNotifier.dispose();
    _zoomNotifier.dispose();
    _flashNotifier.dispose();
    _photoSizeNotifier.dispose();
    super.dispose();
  }
```

1. Create a regular flutter screen.
2. Push the camera screen on top of it.
3. Pop the camera screen.
4. When you are returned to the first screen rotate the device and an exception will be logged because something is calling the orientation notifier:

```
E/flutter (21490): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A ValueNotifier<CameraOrientations> was used after being disposed.
E/flutter (21490): Once you have called dispose() on a ValueNotifier<CameraOrientations>, it can no longer be used.
E/flutter (21490): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter (21490): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter (21490): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
E/flutter (21490): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
E/flutter (21490): #4      _TakePictureScreen4State._buildCameraLayer.<anonymous closure> (package:rapid_on_the_go/screens/camera/take_picture_screen4.dart:82:36)
E/flutter (21490): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (21490): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21490): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (21490): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (21490): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (21490): #10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
E/flutter (21490): #11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter (21490): #12     CamerawesomePlugin.getNativeOrientation.<anonymous closure> (package:camerawesome/camerawesome_plugin.dart:101:14)
E/flutter (21490): #13     _HandlerEventSink.add (dart:async/stream_transformers.dart:225:17)
E/flutter (21490): #14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
E/flutter (21490): #15     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (21490): #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21490): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (21490): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (21490): #19     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (21490): #20     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (21490): #21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (21490): #22     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (21490): #23     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (21490): #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (21490): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (21490): #26     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (21490): #27     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (21490): #28     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (21490): #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (21490): #30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21490): #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

## Expected results

Notifier is not called after the camera screen is closed.

## Actual results

Notifier is called after the camera screen is closed.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Sony* | *Xperia X*  | *Android 8.0*  |

</details>

**Comment by g-apparence** [comment]
Nice bug. Will try to reproduce. 
Or If you have time, you can create a pull request.

**Comment by g-apparence** [comment]
Fixed
