### ISSUE TITLE
Something stops Plugin from working.

### ISSUE THREAD

**Issue by MankoMR** [Apparence-io/camera_awesome#39]
## Steps to Reproduce
[First here is the link to the project:](https://github.com/MankoMR/eartag_reader_prototype/tree/fix-bug)
### With onPermissionResult set
1. Install App
2. Open App
3. Choose "Eartag Reader"
4. One of the follwing Scenario
5. Uninstall App
#### Scenario 1:  Give Permission
```
D/com.apparence.camerawesome.CamerawesomePlugin( 9855): _handleCheckPermissions: 
> W/ActivityThread(32733): SCHED: ch.band.manko.idpa20.eartag_reader_prototype/.MainActivity [84, r=71ms, a=13ms, w=2410ms]
> [log] Permission to access camera: false
```
#### Scenario 2: Deny Permission
```
D/com.apparence.camerawesome.CamerawesomePlugin( 9855): _handleCheckPermissions: 
W/ActivityThread( 6646): SCHED: ch.band.manko.idpa20.eartag_reader_prototype/.MainActivity [74, r=173ms, a=58ms, w=7023ms]
[log] Permission to access camera: false
```
Going a page back and opening "Eartag Reader"
Doesn't call onPermissionsResult anymore:
```
W/ActivityThread( 9855): SCHED: ch.band.manko.idpa20.eartag_reader_prototype/.MainActivity [56, r=26ms, a=20ms, w=45954ms]
D/com.apparence.camerawesome.CamerawesomePlugin( 9855): _handleCheckPermissions: 
W/ActivityThread( 9855): SCHED: ch.band.manko.idpa20.eartag_reader_prototype/.MainActivity [79, r=106ms, a=28ms, w=2890ms]
```
### Without on PermissionResult set
[Git Diff](https://github.com/MankoMR/eartag_reader_prototype/commit/600d474cce918ae55962cc00d3c78a8b13470778l)
1. Install App
2. Open App
3. Choose "Eartag Reader"
4. One of the follwing Scenario
5. Uninstall App
#### Scenario 1:  Give Permission
```
D/com.apparence.camerawesome.CamerawesomePlugin( 7719): _handleCheckPermissions: 
W/ActivityThread( 7719): SCHED: ch.band.manko.idpa20.eartag_reader_prototype/.MainActivity [85, r=170ms, a=29ms, w=57153ms]
E/flutter ( 7719): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter ( 7719): Receiver: null
E/flutter ( 7719): Tried calling: call()
E/flutter ( 7719): #0      CameraAwesomeState.initPlatformState.<anonymous closure> (package:camerawesome/camerapreview.dart:160:37)
E/flutter ( 7719): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 7719): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7719): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 7719): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 7719): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 7719): #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
E/flutter ( 7719): #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 7719): #8      CamerawesomePlugin.listenPermissionResult.<anonymous closure> (package:camerawesome/camerawesome_plugin.dart:111:16)
E/flutter ( 7719): #9      _HandlerEventSink.add (dart:async/stream_transformers.dart:225:17)
E/flutter ( 7719): #10     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
E/flutter ( 7719): #11     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 7719): #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7719): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 7719): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 7719): #15     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter ( 7719): #16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter ( 7719): #17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter ( 7719): #18     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 7719): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7719): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 7719): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 7719): #22     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 7719): #23     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7719): #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 7719): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 7719): #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7719): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 7719): 
W/ActivityThread( 7719): SCHED: ch.band.manko.idpa20.eartag_reader_prototype/.MainActivity [61, r=32ms, a=20ms, w=60911ms]
```
#### Scenario 2: Deny Permission
```
E/flutter ( 8434): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter ( 8434): Receiver: null
E/flutter ( 8434): Tried calling: call()
E/flutter ( 8434): #0      CameraAwesomeState.initPlatformState.<anonymous closure> (package:camerawesome/camerapreview.dart:160:37)
E/flutter ( 8434): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 8434): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 8434): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 8434): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 8434): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 8434): #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
E/flutter ( 8434): #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 8434): #8      CamerawesomePlugin.listenPermissionResult.<anonymous closure> (package:camerawesome/camerawesome_plugin.dart:111:16)
E/flutter ( 8434): #9      _HandlerEventSink.add (dart:async/stream_transformers.dart:225:17)
E/flutter ( 8434): #10     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
E/flutter ( 8434): #11     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 8434): #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 8434): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 8434): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 8434): #15     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter ( 8434): #16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter ( 8434): #17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter ( 8434): #18     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 8434): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 8434): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 8434): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 8434): #22     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 8434): #23     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 8434): #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 8434): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 8434): #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 8434): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
## Expected results
The Plugin should show a preview.
The Flashlight should be toggable.

## Actual results
Nothing.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Xiaomi* | *Redmi Note 7*  | *Android 10, MIUI 12.01*  |

</details>

**Comment by g-apparence** [comment]
Hello, 
which version of the plugin are you using ? (are you on the latest?)

**Comment by MankoMR** [comment]
I have "camerawesome: ^0.1.1+1" as dependency

**Comment by g-apparence** [comment]
after just looking to your code I think you forgot to install permissions in your manifest. 
https://github.com/MankoMR/eartag_reader_prototype/blob/fix-bug/android/app/src/main/AndroidManifest.xml

Follow complete installation there: 
https://pub.dev/packages/camerawesome

**Comment by MankoMR** [comment]
That was indeed the case.
Thank you very much. 😄

**Comment by g-apparence** [comment]
No problem, feel free to ask if you have any other problem.
