### ISSUE TITLE
Android 9: Crash during switch photo to video mode: MissingPluginException(No implementation found for method setCaptureMode on channel camerawesome)

### ISSUE THREAD

**Issue by dundadevelop** [Apparence-io/camera_awesome#75]
## Steps to Reproduce
I am using the current official example. When switching photos to video recording or back, app throw error.
## Actual results
MissingPluginException(No implementation found for method setCaptureMode on channel camerawesome)

in camerapreview.dart (line: 332)

Exception:

E/flutter ( 5590): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method setCaptureMode on channel camerawesome)
E/flutter ( 5590): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter ( 5590): <asynchronous suspension>
E/flutter ( 5590): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter ( 5590): #2      CamerawesomePlugin.setCaptureMode
package:camerawesome/camerawesome_plugin.dart:242
E/flutter ( 5590): #3      CameraAwesomeState._initCaptureMode.<anonymous closure>
package:camerawesome/camerapreview.dart:332
E/flutter ( 5590): #4      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:226
E/flutter ( 5590): #5      ValueNotifier.value=
package:flutter/…/foundation/change_notifier.dart:292
E/flutter ( 5590): #6      _MyAppState._buildInterface.<anonymous closure>
package:camerawesome_example/main.dart:185
E/flutter ( 5590): #7      BottomBarWidget.build.<anonymous closure>
package:camerawesome_example/widgets/bottom_bar.dart:84
E/flutter ( 5590): #8      RenderToggleable._handleTap
package:flutter/…/material/toggleable.dart:416
E/flutter ( 5590): #9      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter ( 5590): #10     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter ( 5590): #11     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter ( 5590): #12     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:259
E/flutter ( 5590): #13     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
E/flutter ( 5590): #14     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:362
E/flutter ( 5590): #15     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter ( 5590): #16     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter ( 5590): #17     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter ( 5590): #18     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter ( 5590): #19     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter ( 5590): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 5590): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5590): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 5590): #23     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 5590): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| Redmi | Note 5  | Android 9 / API 28  |

</details>

Thank you for your time and help.
Zdenek.

**Comment by dundadevelop** [comment]
Ooo, sorry. Video is only for iOS. My stupidity.
