### ISSUE TITLE
NullPointerException in Android & Apps force close

### ISSUE THREAD

**Issue by wisnuwiry** [Apparence-io/camera_awesome#96]
## Steps to Reproduce

- Use `camerawesome` version `0.3.0-nullsafety`
- take the camera normally the same as in the example folder, but run it on the device I mentioned below

## Expected results

Runs normally when takePicture

## Actual results

Apps force close and logs:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.apparence.camerawesome.CameraPreview.access$000(CameraPreview.java)
       at com.apparence.camerawesome.CameraPreview.access$000(CameraPreview.java)
       at com.apparence.camerawesome.CameraPreview$1.onCaptureCompleted(CameraPreview.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


.....

Fatal Exception: java.lang.IllegalStateException: Request has already been finished
       at io.flutter.plugins.camera.PictureCaptureRequest.a(PictureCaptureRequest.java:27)
       at io.flutter.plugins.camera.Camera.a(Camera.java:24)
       at io.flutter.plugins.camera.-$$Lambda$Camera$kpdf-S9lnD9lSxBgWhomOdHv80s.onImageAvailable(-.java:4)
       at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:239)
       at android.app.ActivityThread.main(ActivityThread.java:8179)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *J 2 Prime*  | *6.0.1*  |
| *Vivo* | *1904*  | *11*  |

</details>

**Comment by g-apparence** [comment]
I Think we found it
0.3.0+1 will fix this

Let me know if you encounter this again.
